[2023-03-22 06:19:47,613] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_to_DWlayer.load_to_dw manual__2023-03-22T06:19:38.757121+00:00 [queued]>
[2023-03-22 06:19:47,655] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_to_DWlayer.load_to_dw manual__2023-03-22T06:19:38.757121+00:00 [queued]>
[2023-03-22 06:19:47,656] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-03-22 06:19:47,657] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-03-22 06:19:47,657] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-03-22 06:19:47,683] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_to_dw> on 2023-03-22 06:19:38.757121+00:00
[2023-03-22 06:19:47,692] {standard_task_runner.py:52} INFO - Started process 1338 to run task
[2023-03-22 06:19:47,698] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_to_DWlayer', 'load_to_dw', 'manual__2023-03-22T06:19:38.757121+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_warehouse.py', '--cfg-path', '/tmp/tmpjcvxqh2k', '--error-file', '/tmp/tmpttg9ayrz']
[2023-03-22 06:19:47,699] {standard_task_runner.py:77} INFO - Job 14: Subtask load_to_dw
[2023-03-22 06:19:47,788] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_DWlayer.load_to_dw manual__2023-03-22T06:19:38.757121+00:00 [running]> on host 33f6658fc35a
[2023-03-22 06:19:47,864] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_DWlayer
AIRFLOW_CTX_TASK_ID=load_to_dw
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T06:19:38.757121+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T06:19:38.757121+00:00
[2023-03-22 06:20:02,007] {python.py:152} INFO - Done. Returned value was: None
[2023-03-22 06:20:02,028] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=load_to_DWlayer, task_id=load_to_dw, execution_date=20230322T061938, start_date=20230322T061947, end_date=20230322T062002
[2023-03-22 06:20:02,094] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-22 06:20:02,153] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
