[2023-03-22 08:34:27,823] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_to_datamart.load_to_datamart manual__2023-03-22T08:34:25.490061+00:00 [queued]>
[2023-03-22 08:34:27,850] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: load_to_datamart.load_to_datamart manual__2023-03-22T08:34:25.490061+00:00 [queued]>
[2023-03-22 08:34:27,851] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2023-03-22 08:34:27,852] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2023-03-22 08:34:27,852] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-03-22 08:34:27,868] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_to_datamart> on 2023-03-22 08:34:25.490061+00:00
[2023-03-22 08:34:27,872] {standard_task_runner.py:52} INFO - Started process 792 to run task
[2023-03-22 08:34:27,875] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'load_to_datamart', 'load_to_datamart', 'manual__2023-03-22T08:34:25.490061+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/mart_layer.py', '--cfg-path', '/tmp/tmpbuhvjve0', '--error-file', '/tmp/tmp7ypvssvf']
[2023-03-22 08:34:27,876] {standard_task_runner.py:77} INFO - Job 18: Subtask load_to_datamart
[2023-03-22 08:34:27,920] {logging_mixin.py:109} INFO - Running <TaskInstance: load_to_datamart.load_to_datamart manual__2023-03-22T08:34:25.490061+00:00 [running]> on host 2bbf1c230888
[2023-03-22 08:34:27,969] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=load_to_datamart
AIRFLOW_CTX_TASK_ID=load_to_datamart
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T08:34:25.490061+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T08:34:25.490061+00:00
[2023-03-22 08:34:32,081] {python.py:152} INFO - Done. Returned value was: None
[2023-03-22 08:34:32,097] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=load_to_datamart, task_id=load_to_datamart, execution_date=20230322T083425, start_date=20230322T083427, end_date=20230322T083432
[2023-03-22 08:34:32,144] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-03-22 08:34:32,194] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
